###
GET http://127.0.0.1:3000/api/v1/reviews HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk0MjJlNGY2MTk3MWU4MmQ2NGI5NyIsImlhdCI6MTY3ODA2MTYyOCwiZXhwIjoxNjg1ODM3NjI4fQ.YZDZ1VGypsZdjIaVEjqYBhIFHdxf2PrZbrPb4w7Ve6g

###
GET http://127.0.0.1:3000/api/v1/reviews/64053e07e5a9f2fd5c37809a

###
POST http://127.0.0.1:3000/api/v1/tours/640e0eb7cf333c5ab5cfe137/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGEyM2M4MmY4ZmI4MTRiNTZmYTE4ZCIsImlhdCI6MTY3ODYzMDk5NSwiZXhwIjoxNjg2NDA2OTk1fQ.ncQXkemdvXs851aw4AHdI4Y5yfhzfTOPxU0p_cxym9Q
Content-Type: application/json

{
  "review": "Cras mollis nisi parturient mi nec aliquet suspendisse sagittis eros condimentum scelerisque taciti mattis praesent feugiat eu nascetur a tincidunt",
  "rating": 4
}

###
PATCH http://127.0.0.1:3000/api/v1/reviews/640e0f21cf333c5ab5cfe14a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGEyM2M4MmY4ZmI4MTRiNTZmYTE4ZCIsImlhdCI6MTY3ODYzMDk5NSwiZXhwIjoxNjg2NDA2OTk1fQ.ncQXkemdvXs851aw4AHdI4Y5yfhzfTOPxU0p_cxym9Q
Content-Type: application/json

{
  "review": "Cras mollis nisi parturient mi nec aliquet suspendisse sagittis eros condimentum scelerisque taciti mattis praesent feugiat eu nascetur a tincidunt",
  "rating": 1.6666
}

###
GET http://127.0.0.1:3000/api/v1/tours/64052ee71023066e4f2e3c06/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk0MjJlNGY2MTk3MWU4MmQ2NGI5NyIsImlhdCI6MTY3ODA2MTYyOCwiZXhwIjoxNjg1ODM3NjI4fQ.YZDZ1VGypsZdjIaVEjqYBhIFHdxf2PrZbrPb4w7Ve6g

###
DELETE http://127.0.0.1:3000/api/v1/reviews/640e0ed2cf333c5ab5cfe13a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGEyM2M4MmY4ZmI4MTRiNTZmYTE4ZCIsImlhdCI6MTY3ODYzMDk5NSwiZXhwIjoxNjg2NDA2OTk1fQ.ncQXkemdvXs851aw4AHdI4Y5yfhzfTOPxU0p_cxym9Q